### ISSUE TITLE
Calling the program does not return at all

### ISSUE THREAD

**Issue by LeSpocky** [rohieb/spdx-license-match#1]
When trying `spdx-license-match` on Debian 9 (stretch, amd64) I see the following behaviour, e.g. when calling it as suggested in the README against its own license file like this:

```
spdx-license-match -- LICENSE
```

The command never returns. In htop I see the following:

```
26457 adahl      20   0  4292  1496  1392 S  0.0  0.0  0:00.00 │  │  │        │  └─ sh /home/adahl/bin/spdx-license-match -- LICENSE                             
26468 adahl      20   0  6172   700   620 S  0.0  0.0  0:00.00 │  │  │        │     ├─ fold -w 78 -s
26467 adahl      20   0  4292   124     0 S  0.0  0.0  0:00.00 │  │  │        │     └─ sh /home/adahl/bin/spdx-license-match -- LICENSE
26470 adahl      20   0 23380  3388  3064 S  0.0  0.0  0:00.00 │  │  │        │        ├─ awk  ??END              { if(para!="") print para } ??/^\s+?$/
26469 adahl      20   0  5832   700   624 S  0.0  0.0  0:00.00 │  │  │        │        └─ tr \r \n
```

The same happens when running against other files. If you need more information, let me know.

**Comment by rohieb** [comment]
For the record, the problem here was that `--` threw the option parser off so it did not pass any input to the following processes, which would then wait until forever to get input from stdin.
